spring:
  jpa:
    show-sql: true

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}

logging:
  level:
    com.medtrack: DEBUG
    org.springframework.security: DEBUG
